/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Department = IDL.Text;
export const Location = IDL.Text;
export const CandidateProfile = IDL.Record({
  'cv' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'experience' : IDL.Nat,
  'searchable' : IDL.Bool,
  'contactNumber' : IDL.Text,
  'department' : Department,
  'location' : Location,
});
export const EmployerProfile = IDL.Record({
  'contactEmail' : IDL.Text,
  'companyName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'location' : Location,
  'industry' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'employerId' : IDL.Principal,
  'salaryRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'requiredDepartment' : Department,
  'location' : Location,
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});
export const ApplicationStatus = IDL.Variant({
  'hired' : IDL.Null,
  'interview' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'cv' : IDL.Opt(ExternalBlob),
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'jobId' : IDL.Nat,
  'candidateId' : IDL.Principal,
});
export const UserType = IDL.Variant({
  'employer' : IDL.Null,
  'candidate' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userType' : UserType,
  'name' : IDL.Text,
});
export const Notification = IDL.Record({
  'recipient' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Rating = IDL.Record({
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'ratee' : IDL.Principal,
  'rater' : IDL.Principal,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const LoginResult = IDL.Record({
  'userType' : IDL.Opt(UserType),
  'needsSetup' : IDL.Bool,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminDeleteCandidateProfile' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteEmployerProfile' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteJob' : IDL.Func([IDL.Nat], [], []),
  'adminUpdateCandidateProfile' : IDL.Func(
      [IDL.Principal, CandidateProfile],
      [],
      [],
    ),
  'adminUpdateEmployerProfile' : IDL.Func(
      [IDL.Principal, EmployerProfile],
      [],
      [],
    ),
  'applyForJob' : IDL.Func([IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteJob' : IDL.Func([IDL.Nat], [], []),
  'getAllAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'employers' : IDL.Nat,
          'placementRate' : IDL.Float64,
          'jobPostings' : IDL.Nat,
          'applications' : IDL.Nat,
          'candidates' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllCandidateProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, CandidateProfile))],
      ['query'],
    ),
  'getAllEmployerProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, EmployerProfile))],
      ['query'],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllMyMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getApplicationsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getApplicationsForJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CandidateProfile)],
      ['query'],
    ),
  'getCandidatesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEmployerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EmployerProfile)],
      ['query'],
    ),
  'getEmployersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getJobPostingsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'getPlacementSuccessRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getRatingsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
  'getTopJobRecommendations' : IDL.Func(
      [Location, Department],
      [IDL.Vec(JobPosting)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'login' : IDL.Func([], [LoginResult], []),
  'postJob' : IDL.Func([JobPosting], [IDL.Nat], []),
  'registerCandidate' : IDL.Func([CandidateProfile], [], []),
  'registerEmployer' : IDL.Func([EmployerProfile], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCandidates' : IDL.Func(
      [Department, Location],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'searchJobsByDepartment' : IDL.Func(
      [Department, Location],
      [IDL.Vec(JobPosting)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'sendNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateCandidateProfile' : IDL.Func([CandidateProfile], [], []),
  'updateEmployerProfile' : IDL.Func([EmployerProfile], [], []),
  'updateJob' : IDL.Func([IDL.Nat, JobPosting], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Department = IDL.Text;
  const Location = IDL.Text;
  const CandidateProfile = IDL.Record({
    'cv' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'experience' : IDL.Nat,
    'searchable' : IDL.Bool,
    'contactNumber' : IDL.Text,
    'department' : Department,
    'location' : Location,
  });
  const EmployerProfile = IDL.Record({
    'contactEmail' : IDL.Text,
    'companyName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'location' : Location,
    'industry' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'employerId' : IDL.Principal,
    'salaryRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'requiredDepartment' : Department,
    'location' : Location,
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  const ApplicationStatus = IDL.Variant({
    'hired' : IDL.Null,
    'interview' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
  });
  const JobApplication = IDL.Record({
    'cv' : IDL.Opt(ExternalBlob),
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'jobId' : IDL.Nat,
    'candidateId' : IDL.Principal,
  });
  const UserType = IDL.Variant({
    'employer' : IDL.Null,
    'candidate' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'userType' : UserType, 'name' : IDL.Text });
  const Notification = IDL.Record({
    'recipient' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Rating = IDL.Record({
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'ratee' : IDL.Principal,
    'rater' : IDL.Principal,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const LoginResult = IDL.Record({
    'userType' : IDL.Opt(UserType),
    'needsSetup' : IDL.Bool,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminDeleteCandidateProfile' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteEmployerProfile' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteJob' : IDL.Func([IDL.Nat], [], []),
    'adminUpdateCandidateProfile' : IDL.Func(
        [IDL.Principal, CandidateProfile],
        [],
        [],
      ),
    'adminUpdateEmployerProfile' : IDL.Func(
        [IDL.Principal, EmployerProfile],
        [],
        [],
      ),
    'applyForJob' : IDL.Func([IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteJob' : IDL.Func([IDL.Nat], [], []),
    'getAllAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'employers' : IDL.Nat,
            'placementRate' : IDL.Float64,
            'jobPostings' : IDL.Nat,
            'applications' : IDL.Nat,
            'candidates' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllCandidateProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, CandidateProfile))],
        ['query'],
      ),
    'getAllEmployerProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, EmployerProfile))],
        ['query'],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllMyMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getApplicationsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getApplicationsForJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CandidateProfile)],
        ['query'],
      ),
    'getCandidatesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEmployerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getEmployersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getJobPostingsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPlacementSuccessRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getRatingsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Rating)],
        ['query'],
      ),
    'getTopJobRecommendations' : IDL.Func(
        [Location, Department],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveRating' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'login' : IDL.Func([], [LoginResult], []),
    'postJob' : IDL.Func([JobPosting], [IDL.Nat], []),
    'registerCandidate' : IDL.Func([CandidateProfile], [], []),
    'registerEmployer' : IDL.Func([EmployerProfile], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCandidates' : IDL.Func(
        [Department, Location],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'searchJobsByDepartment' : IDL.Func(
        [Department, Location],
        [IDL.Vec(JobPosting)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'sendNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateCandidateProfile' : IDL.Func([CandidateProfile], [], []),
    'updateEmployerProfile' : IDL.Func([EmployerProfile], [], []),
    'updateJob' : IDL.Func([IDL.Nat, JobPosting], [], []),
  });
};

export const init = ({ IDL }) => { return []; };