/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationStatus = { 'hired' : null } |
  { 'interview' : null } |
  { 'applied' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CandidateProfile {
  'cv' : [] | [ExternalBlob],
  'name' : string,
  'experience' : bigint,
  'searchable' : boolean,
  'contactNumber' : string,
  'department' : Department,
  'location' : Location,
}
export interface ChatMessage {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type Department = string;
export interface EmployerProfile {
  'contactEmail' : string,
  'companyName' : string,
  'contactNumber' : string,
  'location' : Location,
  'industry' : string,
}
export type ExternalBlob = Uint8Array;
export interface JobApplication {
  'cv' : [] | [ExternalBlob],
  'id' : bigint,
  'status' : ApplicationStatus,
  'jobId' : bigint,
  'candidateId' : Principal,
}
export interface JobPosting {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'employerId' : Principal,
  'salaryRange' : [bigint, bigint],
  'requiredDepartment' : Department,
  'location' : Location,
}
export type Location = string;
export interface LoginResult {
  'userType' : [] | [UserType],
  'needsSetup' : boolean,
  'success' : boolean,
}
export interface Notification {
  'recipient' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface Rating {
  'feedback' : string,
  'score' : bigint,
  'ratee' : Principal,
  'rater' : Principal,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'userType' : UserType, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'employer' : null } |
  { 'candidate' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminDeleteCandidateProfile' : ActorMethod<[Principal], undefined>,
  'adminDeleteEmployerProfile' : ActorMethod<[Principal], undefined>,
  'adminDeleteJob' : ActorMethod<[bigint], undefined>,
  'adminUpdateCandidateProfile' : ActorMethod<
    [Principal, CandidateProfile],
    undefined
  >,
  'adminUpdateEmployerProfile' : ActorMethod<
    [Principal, EmployerProfile],
    undefined
  >,
  'applyForJob' : ActorMethod<[bigint, [] | [ExternalBlob]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteJob' : ActorMethod<[bigint], undefined>,
  'getAllAnalytics' : ActorMethod<
    [],
    {
      'employers' : bigint,
      'placementRate' : number,
      'jobPostings' : bigint,
      'applications' : bigint,
      'candidates' : bigint,
    }
  >,
  'getAllCandidateProfiles' : ActorMethod<
    [],
    Array<[Principal, CandidateProfile]>
  >,
  'getAllEmployerProfiles' : ActorMethod<
    [],
    Array<[Principal, EmployerProfile]>
  >,
  'getAllJobs' : ActorMethod<[], Array<JobPosting>>,
  'getAllMyMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getApplicationsCount' : ActorMethod<[], bigint>,
  'getApplicationsForJob' : ActorMethod<[bigint], Array<JobApplication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateProfile' : ActorMethod<[Principal], [] | [CandidateProfile]>,
  'getCandidatesCount' : ActorMethod<[], bigint>,
  'getEmployerProfile' : ActorMethod<[Principal], [] | [EmployerProfile]>,
  'getEmployersCount' : ActorMethod<[], bigint>,
  'getJobPostingsCount' : ActorMethod<[], bigint>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getMyApplications' : ActorMethod<[], Array<JobApplication>>,
  'getNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getPlacementSuccessRate' : ActorMethod<[], number>,
  'getRatingsForUser' : ActorMethod<[Principal], Array<Rating>>,
  'getTopJobRecommendations' : ActorMethod<
    [Location, Department],
    Array<JobPosting>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'leaveRating' : ActorMethod<[Principal, bigint, string], undefined>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'login' : ActorMethod<[], LoginResult>,
  'postJob' : ActorMethod<[JobPosting], bigint>,
  'registerCandidate' : ActorMethod<[CandidateProfile], undefined>,
  'registerEmployer' : ActorMethod<[EmployerProfile], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCandidates' : ActorMethod<[Department, Location], Array<Principal>>,
  'searchJobsByDepartment' : ActorMethod<
    [Department, Location],
    Array<JobPosting>
  >,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'sendNotification' : ActorMethod<[Principal, string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateCandidateProfile' : ActorMethod<[CandidateProfile], undefined>,
  'updateEmployerProfile' : ActorMethod<[EmployerProfile], undefined>,
  'updateJob' : ActorMethod<[bigint, JobPosting], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];