/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Location = string;
export type Time = bigint;
export interface Rating {
    feedback: string;
    score: bigint;
    ratee: Principal;
    rater: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface JobApplication {
    cv?: ExternalBlob;
    id: bigint;
    status: ApplicationStatus;
    jobId: bigint;
    candidateId: Principal;
}
export interface JobPosting {
    id: bigint;
    title: string;
    description: string;
    employerId: Principal;
    salaryRange: [bigint, bigint];
    requiredDepartment: Department;
    location: Location;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type Department = string;
export interface Notification {
    recipient: Principal;
    message: string;
    timestamp: Time;
}
export interface ChatMessage {
    content: string;
    sender: Principal;
    timestamp: Time;
    receiver: Principal;
}
export interface LoginResult {
    userType?: UserType;
    needsSetup: boolean;
    success: boolean;
}
export interface CandidateProfile {
    cv?: ExternalBlob;
    name: string;
    experience: bigint;
    searchable: boolean;
    contactNumber: string;
    department: Department;
    location: Location;
}
export interface EmployerProfile {
    contactEmail: string;
    companyName: string;
    contactNumber: string;
    location: Location;
    industry: string;
}
export interface UserProfile {
    userType: UserType;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApplicationStatus {
    hired = "hired",
    interview = "interview",
    applied = "applied",
    rejected = "rejected",
    shortlisted = "shortlisted"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    employer = "employer",
    candidate = "candidate"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    adminDeleteCandidateProfile(user: Principal): Promise<void>;
    adminDeleteEmployerProfile(user: Principal): Promise<void>;
    adminDeleteJob(jobId: bigint): Promise<void>;
    adminUpdateCandidateProfile(user: Principal, profile: CandidateProfile): Promise<void>;
    adminUpdateEmployerProfile(user: Principal, profile: EmployerProfile): Promise<void>;
    applyForJob(jobId: bigint, cv: ExternalBlob | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteJob(jobId: bigint): Promise<void>;
    getAllAnalytics(): Promise<{
        employers: bigint;
        placementRate: number;
        jobPostings: bigint;
        applications: bigint;
        candidates: bigint;
    }>;
    getAllCandidateProfiles(): Promise<Array<[Principal, CandidateProfile]>>;
    getAllEmployerProfiles(): Promise<Array<[Principal, EmployerProfile]>>;
    getAllJobs(): Promise<Array<JobPosting>>;
    getAllMyMessages(): Promise<Array<ChatMessage>>;
    getApplicationsCount(): Promise<bigint>;
    getApplicationsForJob(jobId: bigint): Promise<Array<JobApplication>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCandidateProfile(user: Principal): Promise<CandidateProfile | null>;
    getCandidatesCount(): Promise<bigint>;
    getEmployerProfile(user: Principal): Promise<EmployerProfile | null>;
    getEmployersCount(): Promise<bigint>;
    getJobPostingsCount(): Promise<bigint>;
    getMessagesWithUser(user: Principal): Promise<Array<ChatMessage>>;
    getMyApplications(): Promise<Array<JobApplication>>;
    getNotifications(limit: bigint): Promise<Array<Notification>>;
    getPlacementSuccessRate(): Promise<number>;
    getRatingsForUser(user: Principal): Promise<Array<Rating>>;
    getTopJobRecommendations(location: Location, department: Department): Promise<Array<JobPosting>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    leaveRating(ratee: Principal, score: bigint, feedback: string): Promise<void>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    login(): Promise<LoginResult>;
    postJob(job: JobPosting): Promise<bigint>;
    registerCandidate(profile: CandidateProfile): Promise<void>;
    registerEmployer(profile: EmployerProfile): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCandidates(department: Department, location: Location): Promise<Array<Principal>>;
    searchJobsByDepartment(department: Department, location: Location): Promise<Array<JobPosting>>;
    sendMessage(receiver: Principal, content: string): Promise<void>;
    sendNotification(recipient: Principal, message: string): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateApplicationStatus(applicationId: bigint, status: ApplicationStatus): Promise<void>;
    updateCandidateProfile(profile: CandidateProfile): Promise<void>;
    updateEmployerProfile(profile: EmployerProfile): Promise<void>;
    updateJob(jobId: bigint, job: JobPosting): Promise<void>;
}
import type { ApplicationStatus as _ApplicationStatus, ApprovalStatus as _ApprovalStatus, CandidateProfile as _CandidateProfile, Department as _Department, EmployerProfile as _EmployerProfile, ExternalBlob as _ExternalBlob, JobApplication as _JobApplication, Location as _Location, LoginResult as _LoginResult, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async adminDeleteCandidateProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteCandidateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteCandidateProfile(arg0);
            return result;
        }
    }
    async adminDeleteEmployerProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteEmployerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteEmployerProfile(arg0);
            return result;
        }
    }
    async adminDeleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteJob(arg0);
            return result;
        }
    }
    async adminUpdateCandidateProfile(arg0: Principal, arg1: CandidateProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCandidateProfile(arg0, await to_candid_CandidateProfile_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCandidateProfile(arg0, await to_candid_CandidateProfile_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminUpdateEmployerProfile(arg0: Principal, arg1: EmployerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateEmployerProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateEmployerProfile(arg0, arg1);
            return result;
        }
    }
    async applyForJob(arg0: bigint, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getAllAnalytics(): Promise<{
        employers: bigint;
        placementRate: number;
        jobPostings: bigint;
        applications: bigint;
        candidates: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnalytics();
            return result;
        }
    }
    async getAllCandidateProfiles(): Promise<Array<[Principal, CandidateProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCandidateProfiles();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCandidateProfiles();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployerProfiles(): Promise<Array<[Principal, EmployerProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployerProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployerProfiles();
            return result;
        }
    }
    async getAllJobs(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return result;
        }
    }
    async getAllMyMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMyMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMyMessages();
            return result;
        }
    }
    async getApplicationsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsCount();
            return result;
        }
    }
    async getApplicationsForJob(arg0: bigint): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForJob(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForJob(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidateProfile(arg0: Principal): Promise<CandidateProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidateProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidateProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCandidatesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCandidatesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCandidatesCount();
            return result;
        }
    }
    async getEmployerProfile(arg0: Principal): Promise<EmployerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployerProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployerProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployersCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployersCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployersCount();
            return result;
        }
    }
    async getJobPostingsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPostingsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPostingsCount();
            return result;
        }
    }
    async getMessagesWithUser(arg0: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesWithUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesWithUser(arg0);
            return result;
        }
    }
    async getMyApplications(): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: bigint): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return result;
        }
    }
    async getPlacementSuccessRate(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlacementSuccessRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlacementSuccessRate();
            return result;
        }
    }
    async getRatingsForUser(arg0: Principal): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingsForUser(arg0);
            return result;
        }
    }
    async getTopJobRecommendations(arg0: Location, arg1: Department): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopJobRecommendations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopJobRecommendations(arg0, arg1);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async leaveRating(arg0: Principal, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRating(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRating(arg0, arg1, arg2);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login();
                return from_candid_LoginResult_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login();
            return from_candid_LoginResult_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async postJob(arg0: JobPosting): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.postJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postJob(arg0);
            return result;
        }
    }
    async registerCandidate(arg0: CandidateProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCandidate(await to_candid_CandidateProfile_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCandidate(await to_candid_CandidateProfile_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerEmployer(arg0: EmployerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerEmployer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerEmployer(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchCandidates(arg0: Department, arg1: Location): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCandidates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCandidates(arg0, arg1);
            return result;
        }
    }
    async searchJobsByDepartment(arg0: Department, arg1: Location): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobsByDepartment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobsByDepartment(arg0, arg1);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async sendNotification(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, arg1);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n48(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n48(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCandidateProfile(arg0: CandidateProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCandidateProfile(await to_candid_CandidateProfile_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCandidateProfile(await to_candid_CandidateProfile_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmployerProfile(arg0: EmployerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployerProfile(arg0);
            return result;
        }
    }
    async updateJob(arg0: bigint, arg1: JobPosting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_CandidateProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CandidateProfile): Promise<CandidateProfile> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_JobApplication_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobApplication): Promise<JobApplication> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CandidateProfile]): Promise<CandidateProfile | null> {
    return value.length === 0 ? null : await from_candid_CandidateProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployerProfile]): EmployerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserType]): UserType | null {
    return value.length === 0 ? null : from_candid_UserType_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cv: [] | [_ExternalBlob];
    name: string;
    experience: bigint;
    searchable: boolean;
    contactNumber: string;
    department: _Department;
    location: _Location;
}): Promise<{
    cv?: ExternalBlob;
    name: string;
    experience: bigint;
    searchable: boolean;
    contactNumber: string;
    department: Department;
    location: Location;
}> {
    return {
        cv: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.cv)),
        name: value.name,
        experience: value.experience,
        searchable: value.searchable,
        contactNumber: value.contactNumber,
        department: value.department,
        location: value.location
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cv: [] | [_ExternalBlob];
    id: bigint;
    status: _ApplicationStatus;
    jobId: bigint;
    candidateId: Principal;
}): Promise<{
    cv?: ExternalBlob;
    id: bigint;
    status: ApplicationStatus;
    jobId: bigint;
    candidateId: Principal;
}> {
    return {
        cv: record_opt_to_undefined(await from_candid_opt_n18(_uploadFile, _downloadFile, value.cv)),
        id: value.id,
        status: from_candid_ApplicationStatus_n23(_uploadFile, _downloadFile, value.status),
        jobId: value.jobId,
        candidateId: value.candidateId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: _UserType;
    name: string;
}): {
    userType: UserType;
    name: string;
} {
    return {
        userType: from_candid_UserType_n28(_uploadFile, _downloadFile, value.userType),
        name: value.name
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n37(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: [] | [_UserType];
    needsSetup: boolean;
    success: boolean;
}): {
    userType?: UserType;
    needsSetup: boolean;
    success: boolean;
} {
    return {
        userType: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.userType)),
        needsSetup: value.needsSetup,
        success: value.success
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _CandidateProfile]): Promise<[Principal, CandidateProfile]> {
    return [
        value[0],
        await from_candid_CandidateProfile_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hired: null;
} | {
    interview: null;
} | {
    applied: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
}): ApplicationStatus {
    return "hired" in value ? ApplicationStatus.hired : "interview" in value ? ApplicationStatus.interview : "applied" in value ? ApplicationStatus.applied : "rejected" in value ? ApplicationStatus.rejected : "shortlisted" in value ? ApplicationStatus.shortlisted : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    employer: null;
} | {
    candidate: null;
}): UserType {
    return "employer" in value ? UserType.employer : "candidate" in value ? UserType.candidate : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _CandidateProfile]>): Promise<Array<[Principal, CandidateProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobApplication>): Promise<Array<JobApplication>> {
    return await Promise.all(value.map(async (x)=>await from_candid_JobApplication_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n35(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_CandidateProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CandidateProfile): Promise<_CandidateProfile> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserProfile_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: UserType;
    name: string;
}): {
    userType: _UserType;
    name: string;
} {
    return {
        userType: to_candid_UserType_n44(_uploadFile, _downloadFile, value.userType),
        name: value.name
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cv?: ExternalBlob;
    name: string;
    experience: bigint;
    searchable: boolean;
    contactNumber: string;
    department: Department;
    location: Location;
}): Promise<{
    cv: [] | [_ExternalBlob];
    name: string;
    experience: bigint;
    searchable: boolean;
    contactNumber: string;
    department: _Department;
    location: _Location;
}> {
    return {
        cv: value.cv ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.cv)) : candid_none(),
        name: value.name,
        experience: value.experience,
        searchable: value.searchable,
        contactNumber: value.contactNumber,
        department: value.department,
        location: value.location
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    employer: null;
} | {
    candidate: null;
} {
    return value == UserType.employer ? {
        employer: null
    } : value == UserType.candidate ? {
        candidate: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    hired: null;
} | {
    interview: null;
} | {
    applied: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
} {
    return value == ApplicationStatus.hired ? {
        hired: null
    } : value == ApplicationStatus.interview ? {
        interview: null
    } : value == ApplicationStatus.applied ? {
        applied: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.shortlisted ? {
        shortlisted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
